services:
  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: hms
      DB_USERNAME: root
      DB_PORT: 3306
      DB_PASSWORD: 12345678
    ports:
        - "8000:8000"
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: hms
    ports: 
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: